# Generated by Django 3.1.7 on 2021-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='movies_app/files')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=400)),
                ('original_title', models.CharField(max_length=400)),
                ('year', models.IntegerField()),
                ('date_published', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('country', models.CharField(max_length=400)),
                ('language', models.CharField(max_length=400)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('production_company', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=600)),
                ('avg_vote', models.FloatField()),
                ('votes', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('usa_gross_income', models.IntegerField()),
                ('worlwide_gross_income', models.IntegerField()),
                ('metascore', models.FloatField()),
                ('reviews_from_users', models.FloatField()),
                ('reviews_from_critics', models.FloatField()),
                ('budget_currency', models.CharField(max_length=100)),
                ('usa_gross_income_currency', models.CharField(max_length=100)),
                ('worlwide_gross_income_currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
